// Code generated by MockGen. DO NOT EDIT.
// Source: parser.go

// Package parse is a generated GoMock package.
package parse

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	apiSpecDoc "github.com/rog-golang-buddies/api-hub_data-scraping-service/internal/dto/apiSpecDoc"
	fileresource "github.com/rog-golang-buddies/api-hub_data-scraping-service/internal/dto/fileresource"
)

// MockParser is a mock of Parser interface.
type MockParser struct {
	ctrl     *gomock.Controller
	recorder *MockParserMockRecorder
}

// MockParserMockRecorder is the mock recorder for MockParser.
type MockParserMockRecorder struct {
	mock *MockParser
}

// NewMockParser creates a new mock instance.
func NewMockParser(ctrl *gomock.Controller) *MockParser {
	mock := &MockParser{ctrl: ctrl}
	mock.recorder = &MockParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParser) EXPECT() *MockParserMockRecorder {
	return m.recorder
}

// GetType mocks base method.
func (m *MockParser) GetType() fileresource.AsdFileType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetType")
	ret0, _ := ret[0].(fileresource.AsdFileType)
	return ret0
}

// GetType indicates an expected call of GetType.
func (mr *MockParserMockRecorder) GetType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockParser)(nil).GetType))
}

// Parse mocks base method.
func (m *MockParser) Parse(ctx context.Context, content []byte) (*apiSpecDoc.ApiSpecDoc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", ctx, content)
	ret0, _ := ret[0].(*apiSpecDoc.ApiSpecDoc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockParserMockRecorder) Parse(ctx, content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockParser)(nil).Parse), ctx, content)
}
